# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20161122_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('diagonal', models.FloatField()),
                ('hdmi_num', models.IntegerField()),
                ('vgs_num', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Brand')),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.UniqueID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('brightness', models.IntegerField()),
                ('hdmi_num', models.IntegerField()),
                ('vgs_num', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Brand')),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.UniqueID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
