# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_monitor_projector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='vgs_num',
            new_name='vga_num',
        ),
    ]
