# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20161123_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projector',
            old_name='vgs_num',
            new_name='vga_num',
        ),
    ]
