# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_auto_20161123_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='unique_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopapp.UniqueID'),
        ),
        migrations.AlterField(
            model_name='projector',
            name='unique_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopapp.UniqueID'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='unique_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopapp.UniqueID'),
        ),
    ]
