# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0006_auto_20161125_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('region', models.GenericIPAddressField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.UniqueID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
