# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_useritems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserItems',
            new_name='UserItem',
        ),
    ]
