# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_auto_20161128_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('region', models.GenericIPAddressField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.UniqueID')),
            ],
        ),
    ]
